name: Build main branch

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Github Packages Publish
        env:
          publishUser: ${{ secrets.FORK_USERNAME }}
          publishPAT: ${{ secrets.FORK_TOKEN }}
        run: ./gradlew publish
